<?php
    if(isset($_POST['btnSubmit'])){
        if(!is_dir('upload')){
            mkdir('upload',0777,true);
        }
        $file=$_FILES['file']['name'];
        $tmp_name=$_FILES['file']['tmp_name'];
        $path='upload/'.$file;
        move_uploaded_file($tmp_name,$path);
    }